name: Scripts

on:
  push:
    branches: main
    paths:
      - .github/workflows/formatter.yml
      - .prettierrc
      - .eslintrc
      - .eslintignore
      - '*.ts'

permissions:
  contents: write

jobs:
  format:
    uses: winstxnhdw/actions/.github/workflows/format-bun.yml@main
