name: Test

on:
  pull_request_target:
    types: [opened]
  pull_request:
    paths:
      - .github/workflows/main.yml
      - .eslintrc
      - .eslintignore
      - tsconfig.json
      - package.json
      - bun.lockb
      - '*.ts'
  push:
    paths:
      - .github/workflows/test.yml
      - .eslintrc
      - .eslintignore
      - tsconfig.json
      - package.json
      - bun.lockb
      - '*.ts'

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/bun.yml@main
    with:
      disable-test: true
      disable-build: true
